service: aws-find-public-ip-instance
provider:
  environment:
    SLACK_URL: ''
    WARN_LIMIT: 0.85
  name: aws
  iam:
    role:
      statements:
        # Allow functions to list all ec2 Instances
        - Effect: Allow
          Action: 'ec2:DescribeInstances'
          Resource: '*'
        - Effect: Allow
          Action: 'ec2:StartInstances'
          Resource: '*'
        - Effect: Allow
          Action: 'ec2:StopInstances'
          Resource: '*'
        - Effect: Allow
          Action: 'ses:GetSendQuota'
          Resource: '*'  
  region: ap-south-1
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  getPublicIp:
    handler: handler.getPublicIp
    events:
      - httpApi:
          path: /
          method: get
  manageInstance:
    handler: handler.manageInstance
    events:
      - httpApi:
          path: /manageInstance
          method: get
  getSESQuota:
    handler: handler.get_ses_quota
    events:
      - schedule: rate(10 minutes)
      - httpApi:
          path: /getSESQuota
          method: get