org: madgicaltechdom
app: aws-find-public-ip-instance
service: aws-find-public-ip-instance
frameworkVersion: '2 || 3'

provider:
  name: aws
  iam:
    role:
      statements:
        # Allow functions to list all ec2 Instances
        - Effect: Allow
          Action: 'ec2:DescribeInstances'
          Resource: '*'
  region: us-east-2
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  getPublicIp:
    handler: handler.getPublicIp
    events:
      - httpApi:
          path: /
          method: get
